export const Landing = '/'
export const SignUp = '/signup'
export const SignIn = '/signin'
export const Demo = '/demo'
export const UserSettings = '/settings/user'
export const BillingSettings = '/settings/billing'
export const ForgotPassword = '/forgot-password'
